# Generated by Django 5.0.6 on 2024-07-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevalimages',
            name='img',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Фото'),
        ),
    ]
